[package]
name = "zk_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tempfile.workspace = true
tempfile = "3.6.0"
assert_cmd = "2.0.8"