[package]
name = "zk_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.6.0"
assert_cmd = "2.0.8"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
