name: PR - with-foundry
on:
  pull_request:
    paths:
      - 'with-foundry/**'

jobs:
  test-with-foundry:
    defaults:
      run:
        working-directory: with-foundry

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest version
        id: versions_step
        run: |
          output=$(node ../.github/scripts/latest.js)
          echo "Output from Node.js script: $output"

          STABLE=$(echo $output | jq -r '.stable')
          echo "::set-output name=stable::$STABLE"

      - name: Set up nargo
        uses: ./.github/actions/setup-nargo
        with:
          version: ${{ steps.versions_step.outputs.stable }}

      - name: Set up foundry
        uses: ./.github/actions/setup-foundry

      - name: Generate verifier contract
        run: |
          nargo codegen-verifier
        working-directory: with-foundry/circuits

      - name: Generate proof
        run: |
          nargo prove
        working-directory: with-foundry/circuits

      - name: Test with Foundry
        run: |
          forge test --optimize --optimizer-runs 5000 --evm-version london
